### ISSUE TITLE
[Bug]: Scheduled transactions appearing as transfers on For budget page

### ISSUE THREAD

**Issue by hapblu** [actualbudget/actual#1026]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When viewing For budget transactions, scheduled transactions do not show payees properly. Instead of the proper payees, transactions appear to be transfers from the same account. Once posted, the correct payee appears.

![image](https://github.com/actualbudget/actual/assets/81502390/95582083-36f9-4c87-9d37-d9ca3ba53ffd)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
I think I introduced this issue by fixing another bug we had for a very long time: https://github.com/actualbudget/actual/pull/955

Will try to take a look at this in the near future.

**Comment by kyrias** [comment]
This appears to already have been fixed.

**Comment by MatissJanis** [comment]
Not fixed

Repro steps:
1. create a schedule that transfers from account A -> B.
2. open `budgeted` page (`/accounts/budgeted`) - observe that the "payee" is the same as "account"; expectation: "payee" !== "account"

**Comment by kyrias** [comment]
Ah, I misread the description and thought this was about them showing up as transfers when they weren't.  Then this is the same as #1333.

**Comment by kyrias** [comment]
Actually, re-reading the description it seems like this _was_ about them showing explicitly as transfers from the account, but currently they just show the payee incorrectly but not as a transfer, so _partially_ fixed.
