### ISSUE TITLE
[Bug]: Import CSV not splitting on selected Delimiter

### ISSUE THREAD

**Issue by HBDK** [actualbudget/actual#1793]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After updating to 23.10 the values shown in the Date, Payee, Notes and Amount drop downs are split on Comma and not the Delimiter selected in the Delimiter drop down.

when i downgrade to 23.9 it splits on the selected delimiter as expected.

changing the delimiter does not change it and i see no errors in the browser console.

![Screenshot from 2023-10-14 14-58-17](https://github.com/actualbudget/actual/assets/1486019/5a7ec02b-d441-461f-820f-9f823f542177)

i'm running Firefox 115.0

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by hippalectryon-0** [comment]
Can confirm, same here

**Comment by hippalectryon-0** [comment]
Actually, I believe this is the same as #1774 , so it should be fixed

**Comment by MikesGlitch** [comment]
Can you give us a test file? And does the file you're using have headers? If it doesn't have headers you should untick the "File has header row" option.

I tried with this file and it worked fine:
[Semicolon.csv](https://github.com/actualbudget/actual/files/13193211/Semicolon.csv)

![image](https://github.com/actualbudget/actual/assets/5285928/e2cdb57c-9a68-4c01-9a63-2f9f0e209fde)

**Comment by Marcus-Schubert** [comment]
As of today and running the latest available version (v23.10.0) I can confirm that this bug still exists.

**Comment by MikesGlitch** [comment]
> As of today and running the latest available version (v23.10.0) I can confirm that this bug still exists.

I think this is fixed in the next release which will be v23.11.1. I think that'll get released in the next week or so.

**Comment by sndrmate** [comment]
I found actualbudget today and struggled for almost three hours to import the csv before I found this bug report.

Looks like I will start using it next week...

**Comment by jlsjonas** [comment]
I actually seem to have a very related but worse issue since 23.10.0 (23.11.0 isn't available yet on truecharts to validate on there; posting for documentation purposes if the issue persists)

Using the following dummy csv:
```csv
"Uittreksel";"Datum";"Valuta datum";"Rekening";"Beschrijving";"Bedrag";"Valuta"
"2023/0010/0002";"31/10/2023";"31/10/2023";"";"Foo";"+ 123,12";"EUR"
"2023/0010/0001";"21/10/2023";"21/10/2023";"";"Bar";"- 1,23";"EUR"
```
it results in:
![image](https://github.com/actualbudget/actual/assets/932193/0f27604f-787b-40b5-b457-be9bfb2d8cee)


As my csv contains quotes, I suspect that the underlying issue will also be the delimiter selector (it is expecting a delimiter and seeing `;` --the delimiter-- after all.

**Comment by jlsjonas** [comment]
👍 Confirmed working on my side too!
I suspect the underlying issue will also be resolved for the issue author.

**Comment by HBDK** [comment]
Sorry for the late reply, I finally got around to upgrading my instance and the error appears to be fixed now.
