### ISSUE TITLE
Import does not work when semicolon is used as delimiter in .csv file

### ISSUE THREAD

**Issue by juriroemer** [actualbudget/actual#19]
I get the following error when i try to import a .csv that uses semicolons as a delimiter:

![image](https://user-images.githubusercontent.com/31971585/166104229-e6179bf3-edba-4b14-940d-306ca843a308.png)

Replacing the semicolons with commas fixes it. But at the same time the `Import transactions (CSV)` dialog (which I only get to after replacing semicolons with commas) gives me the option to use semicolons as delimiter:

![Bildschirmfoto 2022-04-30 um 13 50 22](https://user-images.githubusercontent.com/31971585/166104535-b8542722-67b0-4c4c-974c-9ff0a2feb21a.png)

**Comment by johan-lejdung** [comment]
I had the same issue, I think it has to do with certain characters. Weirdly it passes if I open and save it again from Numbers even with semicolon

**Comment by DesignsWithDavid** [comment]
As a temporary work-around, open a text editor and do a "find-all and replace" to make it comma delimited

**Comment by johan-lejdung** [comment]
> As a temporary work-around, open a text editor and do a "find-all and replace" to make it comma delimited

Pretty sure I tried that already, that would be very interesting if it worked. 

Will give it a try and report back

**Comment by arhu32** [comment]
> As a temporary work-around, open a text editor and do a "find-all and replace" to make it comma delimited

A more permanent work-around:

1. remove all quote characters in the CSV file (search and replace-all)
2. on the import window in Actual set everything to your liking, including a semicolon as delimiter
3. import

These settings persist. From then on  you can import to this account without having to edit the settings or the file again.

**Comment by MatissJanis** [comment]
👋 Are you still able to reproduce the issue on the latest version ([demo app](https://actualbudget.netlify.app/))? For me this seems to have been fixed. 

If you're still able to reproduce - would you mind attaching an example CSV file that breaks?

**Comment by johan-lejdung** [comment]
Still getting an error on my end using Safari at least. But it works when I reduce the number of rows, this is probably just the bug I experienced before on Safari where the frontend isn't able to handle rows because of some poorly written code that overloads the browser cache reported here https://github.com/actualbudget/actual/issues/21
<img width="561" alt="Screenshot 2023-03-10 at 10 39 52" src="https://user-images.githubusercontent.com/9266884/224280946-1a97dcb0-f55b-4720-aef3-9db26873c791.png">

Here is a sample CSV that causes the error
[error-actual-budget-file.csv](https://github.com/actualbudget/actual/files/10940664/error-actual-budget-file.csv)

**Comment by j-f1** [comment]
Thanks for the info! I think that issue will be fixed with the new version, but this issue should be fixed by https://github.com/actualbudget/actual/pull/738.
