### ISSUE TITLE
[Bug]: Dark Mode - Missed text contrast issue

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2020]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The text on the red missed pill is really hard to read against that selection of background. 

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/22135084/7b2ad42b-86de-4922-802b-3b1af8fa406e)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
fixed by #2048

**Comment by rich-howell** [comment]
> fixed by #2048

Tested your deploy and it is still a problem 

![image](https://github.com/actualbudget/actual/assets/22135084/b3fcf7b4-9aad-4de5-b405-1e740e843c4c)

**Comment by carkom** [comment]
Hadn't pushed my commit yet. Can you check now? Cheers!

**Comment by rich-howell** [comment]
> Hadn't pushed my commit yet. Can you check now? Cheers!

That is better :)
