### ISSUE TITLE
[Bug]: Reconciled transactions should not be duplicated as such

### ISSUE THREAD

**Issue by tavlima** [actualbudget/actual#2155]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Given the reconciled state of a transactions cannot be removed (which I think should be possible, but that is another discussion), the resulting transaction from duplicating an existing reconciled transaction should NOT be automatically flagged as reconciled. IMHO, it should be `uncleared`, for consistency.

### Where are you hosting Actual?

Fly.io

### Operating System

None

**Comment by MatissJanis** [comment]
Locked transactions should in fact be unlock-able. Though nobody has built the feature yet :) 

Would that solve your problem?

**Comment by MatissJanis** [comment]
Unlocking should solve the problem. Closing this since there is no response from OP.

**Comment by mekkanik-mike** [comment]
Unlocking locked transactions doesn't quite solve the issue and adds an unnecessary step when duplicating an existing transaction. My usual need for having to do so would be a similar transaction in the recent past that I need to repeat for today. Only the date would change.

**Comment by nardz13** [comment]
just adding my voice to this - very much an issue as i quite often duplicate recurring transactions (where schedule is not already set up) and it brings my reconciliation out until i catch up the rest of the transactions.
