### ISSUE TITLE
[Bug]: Desktop app on macOS budget loading error 

### ISSUE THREAD

**Issue by Stryd3r** [actualbudget/actual#2705]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I successfully downloaded the desktop app on my Mac and when I connect to my fly.io account and load the budget I’m getting an error. Errors are “We had an unknown problem opening “My Finance dcb1c51” and I’m also unable to browse to the exported .json file. Occasionally I’m also getting the “something went wrong trying to download that file error”. 

Additional information:
I’m facing this issue on- Client version: v24.5.0
Server version: v24.5.0

Screenshots attached. 
![Image 04-05-2024 at 1 00 AM](https://github.com/actualbudget/actual/assets/161248978/f57ba166-04de-47f0-b264-cf5d8ecdb5c6)
![IMG_4405](https://github.com/actualbudget/actual/assets/161248978/6d6287ec-59f9-496a-8083-aef9f3942cd7)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by cjtodaro** [comment]
I'm having the same issue. Trying to run desktop app on MacOS 14.4.1. ActualBudget hosted on unRAID 6.12.8

The error message file name doesn't match the budget file I'm trying to open either.

![Screenshot 2024-05-04 at 2 22 46 PM](https://github.com/actualbudget/actual/assets/64548487/501f79e1-4837-48ff-8850-9d88df9b4ee0)

**Comment by FeralFlora** [comment]
I have a similar issue on Windows 11, but in my case, the download load screen just goes on forever:
![Actual_31mGsjDGZP](https://github.com/actualbudget/actual/assets/33608083/091c6e40-92ab-4657-b8e5-a609ad011cde)

My Actual server is hosted on Pikapods, and the server version is 24.4.

**Comment by lukebouch** [comment]
I'm having the same issue.

**Comment by moobaabaa** [comment]
Same with desktop app. Browser access works fine. 

![Actual](https://github.com/actualbudget/actual/assets/62554223/0883bf9b-690f-403f-9ba3-464276caf244)

**Comment by youngcw** [comment]
Can someone try out the build available here and confirm if its working for you or not? https://github.com/actualbudget/actual/actions/runs/8971187425?pr=2715

It should fix the loading issue.  You will need to download the file listed as "actual-electron-macos-latest".  That is a zip file that contains the desktop app.

**Comment by cjtodaro** [comment]
> Can someone try out the build available here and confirm if its working for you or not? https://github.com/actualbudget/actual/actions/runs/8971187425?pr=2715
> 
> It should fix the loading issue. You will need to download the file listed as "actual-electron-macos-latest". That is a zip file that contains the desktop app.

That fixed it for me!

**Comment by moobaabaa** [comment]
Excellent! Thanks for the updated file. Works for me.

**Comment by psybers** [comment]
This seems to be broken again.

**Comment by MatissJanis** [comment]
Ok, so I'm really confused. Building the desktop app locally works just fine. Building the same source via CI/CD - creates a broken build.

Code signing and other things are all turned off. So I'm really lost as to what is going on which makes it very hard to debug and patch the issue.

**Comment by youngcw** [comment]
@MatissJanis Could you upload a good working build to the release? That way people can use it while we try to determine why the autobuild is broken.

**Comment by MatissJanis** [comment]
Good idea. Uploaded my local build to the release as a temporary solution: https://github.com/actualbudget/actual/releases/tag/v24.6.0

**Comment by MatissJanis** [comment]
@youngcw had a brilliant idea: the issue might have to do with the Github CI runners.

Here's a CI job that was building a working artefact: https://github.com/actualbudget/actual/actions/runs/8971187425

So I re-ran the same exact job and it failed: https://github.com/actualbudget/actual/actions/runs/8971187425

This points to the issue being in the runner. Now we just need to figure out **what changed** and **how to change it back**.

**Comment by psybers** [comment]
@MatissJanis I would guess the issue is the non-pinned OS version:

The passing run:

```
Operating System
  macOS
  14.4.1
  2[3](https://github.com/actualbudget/actual/actions/runs/8971187425/job/24636381309#step:1:3)E224
Runner Image
  Image: macos-1[4](https://github.com/actualbudget/actual/actions/runs/8971187425/job/24636381309#step:1:4)-arm64
  Version: 20240422.3
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm[6](https://github.com/actualbudget/actual/actions/runs/8971187425/job/24636381309#step:1:7)4/20240422.3/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3
```

and the failing run:

```
Operating System
  macOS
  14.5
  2[3](https://github.com/actualbudget/actual/actions/runs/8971187425/job/25863389615#step:1:3)F79
Runner Image
  Image: macos-1[4](https://github.com/actualbudget/actual/actions/runs/8971187425/job/25863389615#step:1:4)-arm64
  Version: 20240[6](https://github.com/actualbudget/actual/actions/runs/8971187425/job/25863389615#step:1:7)03.1
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240603.1/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240603.1
```

What exactly changed in macOS that is causing the issue, I do not know.  But other than that, and the fact the artifact size is slightly different, I do not spot any differences in the logs of the two runs.

**Comment by MatissJanis** [comment]
Any ideas how to pin to a specific runner version?

**Comment by youngcw** [comment]
Looks like we can only pin to major versions so even if we specified macos-14 we would probably still have the same issue

**Comment by youngcw** [comment]
Maybe this project could help. https://github.com/pd4d10/debugtron

**Comment by psybers** [comment]
> Any ideas how to pin to a specific runner version?

AFAIK you can not. You can only select major release, e.g. `-13` or `-14` instead of `-latest`.

**Comment by psybers** [comment]
I used the debugtron and see this when opening a local file:

```
[Exception] Error: dlopen(/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS, 0x0001): tried: '/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS' (no such file), '/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/private/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS' (no such file), '/private/var/folders/gf/vvdfvl3939lgvrcnb11djrgsxvgdnv/T/.com.actualbudget.actual.hUXpBS' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at bindings (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by psybers** [comment]
Have we ever confirmed if the mac images fail on both Intel and M1/M2 macs?  I am on an Intel mac.

GitHub's latest macos image is arm only.

**Comment by MatissJanis** [comment]
I'm on Intel too.

**Comment by cpisto** [comment]
I'm on Apple silicon and the original released 24.6.0 image fails for me, suggesting it is not an architecture specific issue.

**Comment by MatissJanis** [comment]
Maybe related: https://github.com/actions/runner-images/issues/9995

**Comment by cpisto** [comment]
Between 24.5.0 and 24.6.0 better-sqlite3 was upgraded from 9.3.0 to 9.6.0, between those versions better-sqlite3 was updated to support native arm builds on macOS, perhaps something there broke there if the GitHub runner changed from x86 to arm between working and not working?

**Comment by youngcw** [comment]
Maybe we need to setup the workflow to have two runners, one for arm one for x86.

**Comment by MatissJanis** [comment]
> Between 24.5.0 and 24.6.0 better-sqlite3 was upgraded from 9.3.0 to 9.6.0, between those versions better-sqlite3 was updated to support native arm builds on macOS, perhaps something broke there if the GitHub runner changed from x86 to arm between working and not working?

That's not it. We narrowed it down to the github-runner being at fault here, not the dependency upgrade. See [this comment](https://github.com/actualbudget/actual/issues/2705#issuecomment-2150990394).

**Comment by cpisto** [comment]
Definitely strange. The dlopen error on psyber's debugtron seems to indicate the x86 binary is trying to dlopen an arm lib. I'm curious if an arm binary built on an arm runner would work.

**Comment by MatissJanis** [comment]
I tried a few things here: https://github.com/actualbudget/actual/pull/2849

- manually set XCode version to 15.4
- changed macos runner version to 13
- changed macos runner version to 14 (pinned, but basically the same as `latest` at this point)
- changed macos runner to use `large` instance (which theoretically should pick up arm64) - our open source license does not allow using large instances

Out of ideas at this point.

**Comment by cpisto** [comment]
Maybe set the system architecture for the setup-node action to x86 or x64? It defaults to the runner architecture which is arm for -latest.

**Comment by MatissJanis** [comment]
No bueno: https://github.com/actualbudget/actual/pull/2849

**Comment by cpisto** [comment]
This is quite the rabbit hole. I'm wondering if the actions/cache is caching the node_modules from the previous arm node runtime. Something like this:

https://github.com/vitejs/vite-plugin-react-swc/issues/74

**Comment by cpisto** [comment]
It looks like it is- the cache key is only based on the os, not the architecture. So the now x86/x64 node runtime is using the cached node_modules for arm, which is likely where the "Bindings not found." error is coming from during the Electron build step.

**Comment by tdeebswihart** [comment]
I'm encountering this on the most recently released version:
```
Actual.app/Contents/MacOS took 6s
$ ./Actual
[Exception] Error: dlopen(/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V, 0x0001): tried: '/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V' (no such file), '/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/private/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V' (no such file), '/private/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

```
$ file /var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V
/var/folders/hg/lsbm785s2p7g5t7ltsw8ddnr0000gn/T/.com.actualbudget.actual.J0n83V: Mach-O 64-bit bundle x86_64
```

**Comment by Neosaurus** [comment]
I'm experiencing this bug on the latest version also.

**Comment by geeklihui** [comment]
Same here, version: 24.8.0
M1 Macbook Pro.
Running in locally.
<img width="260" alt="图片" src="https://github.com/user-attachments/assets/ec180ffb-7222-4751-8d33-99f8ee4eda29">

**Comment by Kidglove57** [comment]
> Same here, version: 24.8.0 M1 Macbook Pro. Running in locally. <img alt="图片" width="260" src="https://private-user-images.githubusercontent.com/28993319/356124587-ec180ffb-7222-4751-8d33-99f8ee4eda29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTM3NTEsIm5iZiI6MTcyMzExMzQ1MSwicGF0aCI6Ii8yODk5MzMxOS8zNTYxMjQ1ODctZWMxODBmZmItNzIyMi00NzUxLThkMzMtOTlmOGVlNGVkYTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDEwMzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZDQ5MzAyMDZlMmVkYjBjOTNmODc1NDNlNzlhYzY0ZjRiNGRjZDhjNDUzMTZiOGQ4NzcwM2ZiOWQ3ZGIyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vR0Vo6fWnMzxUwjdc--N3ebT376HswrSUQti6jpaTnU">

This might just be the error I had on Silicon? Solved for me by enabling Rosetta for now.

**Comment by geeklihui** [comment]
> Same

Are you using the latest version too? If so, then maybe relative with chip type. I'm using M1Pro with Rosetta on. But why it need Rosetta? It's arm architecture.

<img width="960" alt="图片" src="https://github.com/user-attachments/assets/cd2af811-5446-4838-b4f7-1b55674c14e9">

**Comment by MikesGlitch** [comment]
I've got a fresh build up here: https://github.com/actualbudget/actual/actions/runs/10319828575?pr=3220

I'm looking for 2 testers, one with a x64 machine and one with an arm64 machine.

I'm expecting the x64 machine to work and the arm64 machine to fail - but want to double check before I try anything else.

For the testers:

Can you install the dmg file appropriate for your arch - there's 2: x64 and arm64

**Comment by MikesGlitch** [comment]
To keep this thread in the loop, I think it's fixed here:

https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220

For those with Arm CPU's, can you try out the latest build and tell me what you see?

I think _some_ of you may see "this file is damaged" due to some Apple nonsense about notarizing the app (we plan on fixing that).

If you see the damaged file warning, I think running the below command will fix it:

```
 xattr -c <path/to/application.app>
```

**Comment by trebor1110** [comment]
Hello @MikesGlitch ,

I just downloaded and installed the current Release today [v24.8.0].

I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.

Machine:
Macbook Pro M3

**Comment by MikesGlitch** [comment]
> Hello @MikesGlitch ,
> 
> I just downloaded and installed the current Release today [v24.8.0].
> 
> I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> 
> Machine: Macbook Pro M3

Thanks for checking. I think I fixed it here, can I get someone to try again?

https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220

Sorry for all this back and forward, I don't have a Arm64 mac 😢

**Comment by MatissJanis** [comment]
> Thanks for checking. I think I fixed it here, can I get someone to try again?
> 
> https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> 
> Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.

✅  This works on Intel if that helps (don't have an ARM machine).

**Comment by MikesGlitch** [comment]
I have a PR up with the fix, thanks everyone for the help! 🚀

**Comment by MikesGlitch** [comment]
Fixed by https://github.com/actualbudget/actual/pull/3220

**Comment by geeklihui** [comment]
> To keep this thread in the loop, I think it's fixed here:
> 
> https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220
> 
> For those with Arm CPU's, can you try out the latest build and tell me what you see?
> 
> I think _some_ of you may see "this file is damaged" due to some Apple nonsense about notarizing the app (we plan on fixing that).
> 
> If you see the damaged file warning, I think running the below command will fix it:
> 
> ```
>  xattr -c <path/to/application.app>
> ```
> 
> Can someone confirm?

It worked for me too! (M1Pro) Thanks!

**Comment by Neosaurus** [comment]
> > Hello @MikesGlitch ,
> > I just downloaded and installed the current Release today [v24.8.0].
> > I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> > Machine: Macbook Pro M3
> 
> Thanks for checking. I think I fixed it here, can I get someone to try again?
> 
> https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> 
> Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.

Sadly still present for me :( Also M1 pro MBP 14"

**Comment by MikesGlitch** [comment]
> > > Hello @MikesGlitch ,
> > > I just downloaded and installed the current Release today [v24.8.0].
> > > I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> > > Machine: Macbook Pro M3
> > 
> > 
> > Thanks for checking. I think I fixed it here, can I get someone to try again?
> > https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> > Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.
> 
> Sadly still present for me :( Also M1 pro MBP 14"

What error do you get?

**Comment by Kidglove57** [comment]
I'm testing the latest build on my M2 Mac. As expected I get the damaged file message. I tried running the command you mentioned. However Terminal is throwing an error:
zsh parse error near \n

**Comment by MikesGlitch** [comment]
Are you running the command with the <> brackets? If you remove them it should work

A real life command might looik similar to
```
 xattr -c path/to/Actual.app
```

**Comment by Neosaurus** [comment]
> > > > Hello @MikesGlitch ,
> > > > I just downloaded and installed the current Release today [v24.8.0].
> > > > I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> > > > Machine: Macbook Pro M3
> > > 
> > > 
> > > Thanks for checking. I think I fixed it here, can I get someone to try again?
> > > https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> > > Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.
> > 
> > 
> > Sadly still present for me :( Also M1 pro MBP 14"
> 
> Can you confirm that you have the latest artefact and have run the command? If so, what error do you get?

The same as before, with an "unknown error opening x file". My server is running the latest version. I had to run the xattr command to get it to work

**Comment by MikesGlitch** [comment]
> > > > > Hello @MikesGlitch ,
> > > > > I just downloaded and installed the current Release today [v24.8.0].
> > > > > I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> > > > > Machine: Macbook Pro M3
> > > > 
> > > > 
> > > > Thanks for checking. I think I fixed it here, can I get someone to try again?
> > > > https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> > > > Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.
> > > 
> > > 
> > > Sadly still present for me :( Also M1 pro MBP 14"
> > 
> > 
> > Can you confirm that you have the latest artefact and have run the command? If so, what error do you get?
> 
> The same as before, with an "unknown error opening x file". My server is running the latest version. I had to run the xattr command to get it to work

This is odd because others have reported it working - and an arm64 should work the same no matter what machine its on. 

Can you try re-downloading it from https://github.com/actualbudget/actual/releases/tag/v24.8.0 ? 

If you still get the error can you open up devtools by clicking the view and "toggle devtools" until you get the error and screen grab it for me?

**Comment by Kidglove57** [comment]
Still struggling a bit in terminal so?
xattr -c applications/actual.app

**Comment by MikesGlitch** [comment]
For me it was: 

```
xattr -c /applications/actual.app
```

**Comment by MikesGlitch** [comment]
> Still struggling a bit in terminal so? xattr -c applications/actual.app

For me it was: 

```
xattr -c /applications/actual.app
```

**Comment by Kidglove57** [comment]
> xattr -c /applications/actual.app

Thank you for persevering with me. I'm not sure what I was doing wrong - maybe incorrect spacing in the command. Anyhow, now working really well and I can confirm that export works too. 

Just in case others are reading this - don't expect any response when you enter this command in terminal. But it does work

**Comment by Neosaurus** [comment]
> > > > > > Hello @MikesGlitch ,
> > > > > > I just downloaded and installed the current Release today [v24.8.0].
> > > > > > I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> > > > > > Machine: Macbook Pro M3
> > > > > 
> > > > > 
> > > > > Thanks for checking. I think I fixed it here, can I get someone to try again?
> > > > > https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> > > > > Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.
> > > > 
> > > > 
> > > > Sadly still present for me :( Also M1 pro MBP 14"
> > > 
> > > 
> > > Can you confirm that you have the latest artefact and have run the command? If so, what error do you get?
> > 
> > 
> > The same as before, with an "unknown error opening x file". My server is running the latest version. I had to run the xattr command to get it to work
> 
> This is odd because others have reported it working - and an arm64 should work the same no matter what machine its on.
> 
> Can you try removing it from your system, then re-downloading it from https://github.com/actualbudget/actual/releases/tag/v24.8.0 ?
> 
> If you still get the error can you open up devtools by clicking the "View" menu > "toggle devtools" > "Console" until you get the error and screen grab it for me?

Here is the error:
![CleanShot 2024-08-15 at 11 05 18@2x](https://github.com/user-attachments/assets/b6149e4a-b38e-444e-9a17-519ea729df92)
I can confirm via Activity Monitor that this is the Apple Silicon release. The server runs on my x86 home server though, which could be the issue?

**Comment by MikesGlitch** [comment]
> > > > > > > Hello @MikesGlitch ,
> > > > > > > I just downloaded and installed the current Release today [v24.8.0].
> > > > > > > I still have this error. However, as advised by @Kidglove57 above, I enabled Rosetta and that resolved the issue for now.
> > > > > > > Machine: Macbook Pro M3
> > > > > > 
> > > > > > 
> > > > > > Thanks for checking. I think I fixed it here, can I get someone to try again?
> > > > > > https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220
> > > > > > Apologies for all this back and forward, I don't have a Arm64 mac so can't do it myself.
> > > > > 
> > > > > 
> > > > > Sadly still present for me :( Also M1 pro MBP 14"
> > > > 
> > > > 
> > > > Can you confirm that you have the latest artefact and have run the command? If so, what error do you get?
> > > 
> > > 
> > > The same as before, with an "unknown error opening x file". My server is running the latest version. I had to run the xattr command to get it to work
> > 
> > 
> > This is odd because others have reported it working - and an arm64 should work the same no matter what machine its on.
> > Can you try removing it from your system, then re-downloading it from https://github.com/actualbudget/actual/releases/tag/v24.8.0 ?
> > If you still get the error can you open up devtools by clicking the "View" menu > "toggle devtools" > "Console" until you get the error and screen grab it for me?
> 
> Here is the error: ![CleanShot 2024-08-15 at 11 05 18@2x](https://private-user-images.githubusercontent.com/8516727/358189487-b6149e4a-b38e-444e-9a17-519ea729df92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTg4OTQsIm5iZiI6MTcyMzcxODU5NCwicGF0aCI6Ii84NTE2NzI3LzM1ODE4OTQ4Ny1iNjE0OWU0YS1iMzhlLTQ0NGUtOWExNy01MTllYTcyOWRmOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTA0MzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTExOTBkNzU1OTFmNTJlMTE5OTc4NjE1NjllZGY2MWI1ZDIwMjdiZjMyNGMyMzBjNzI5YmQxNjc1NzNjOWY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CKIaAQdAwVGhOBrdSlLG92zwkhVB1_HCDTSjoh4-tDI) I can confirm via Activity Monitor that this is the Apple Silicon release. The server runs on my x86 home server though, which could be the issue?
> 
> The previous release still works fine.
> 
> Edit: actually I see I'm using the intel release (unbeknownst to me) for the previous version - do I need to match the server architecture and my laptop architecture?

Can we take this to Discord? Hard to have a convo on Github. 

Here's the link to the support thread: https://discord.com/channels/937901803608096828/1271969489294200883

**Comment by geeklihui** [comment]
> > To keep this thread in the loop, I think it's fixed here:
> > https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220
> > For those with Arm CPU's, can you try out the latest build and tell me what you see?
> > I think _some_ of you may see "this file is damaged" due to some Apple nonsense about notarizing the app (we plan on fixing that).
> > If you see the damaged file warning, I think running the below command will fix it:
> > ```
> >  xattr -c <path/to/application.app>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can someone confirm?
> 
> It worked for me too! (M1Pro) Thanks!

Hello @MikesGlitch, not sure if it related to this issue, but the export was error in macOS.
<img width="540" alt="图片" src="https://github.com/user-attachments/assets/cf239600-7a70-45fa-9465-3f30b692911e">

debug info:
<img width="545" alt="图片" src="https://github.com/user-attachments/assets/81507fc9-720a-454e-a3be-4db54264a854">

**Comment by MikesGlitch** [comment]
> > > To keep this thread in the loop, I think it's fixed here:
> > > https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220
> > > For those with Arm CPU's, can you try out the latest build and tell me what you see?
> > > I think _some_ of you may see "this file is damaged" due to some Apple nonsense about notarizing the app (we plan on fixing that).
> > > If you see the damaged file warning, I think running the below command will fix it:
> > > ```
> > >  xattr -c <path/to/application.app>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Can someone confirm?
> > 
> > 
> > It worked for me too! (M1Pro) Thanks!
> 
> Hello @MikesGlitch, not sure if it related to this issue, but the export was error in macOS. <img alt="图片" width="540" src="https://private-user-images.githubusercontent.com/28993319/358884706-cf239600-7a70-45fa-9465-3f30b692911e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjYxNDMsIm5iZiI6MTcyMzk2NTg0MywicGF0aCI6Ii8yODk5MzMxOS8zNTg4ODQ3MDYtY2YyMzk2MDAtN2E3MC00NWZhLTk0NjUtM2YzMGI2OTI5MTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YWQzY2U2ZWFlMmM2MDQxZjhiN2VmOWM0YmMzNjRjMDAzM2ViY2E5NTFiYjAyYjQ1ZDAzMGRkNGE5NGJiNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sOM3ViFHYBVIj_-VYZwtTdnUw6XBwu9mGmylAf1Tg9Y">
> 
> debug info: <img alt="图片" width="545" src="https://private-user-images.githubusercontent.com/28993319/358884764-81507fc9-720a-454e-a3be-4db54264a854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NjYxNDMsIm5iZiI6MTcyMzk2NTg0MywicGF0aCI6Ii8yODk5MzMxOS8zNTg4ODQ3NjQtODE1MDdmYzktNzIwYS00NTRlLWEzYmUtNGRiNTQyNjRhODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA3MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTE0YWVkMWY1YjVkNjI1MWQxNDMzODJmZjBlMjMwY2VlNTI1OGI5YTliNTgwNzBiNjU5NjVjMTdlMzFjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PILxoWSTqvjzERVYwIGo4gSdRqUqncmQ8T_JGXkp14w">

That error was unrelated, but it's fixed in the latest release as well (you'll have to re-download). 

We also have automatic backups in the Electron app - there's not much reason to do a manual export 👍
