### ISSUE TITLE
[Bug]: We had an unknown problem opening "<local actual file>"

### ISSUE THREAD

**Issue by mt-TechJourney** [actualbudget/actual#3199]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

This is my local actual db that I use to manage my finances. 
![Untitled](https://github.com/user-attachments/assets/7e987270-87d0-4a1f-ab00-8740660027b4)

After the latest update (v24.8.0) which I downloaded from the GitHub repository, the application fails to read my database and gives me an error.
<img width="901" alt="image" src="https://github.com/user-attachments/assets/bdab0fe9-823f-4241-961c-31b19452c44c">

Even if I try to create a new local actual file, it is still giving me the same error as shown in the screenshot above. I have installed the previous version for now since that is not giving me an error (v24.7.0)

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Other

### Operating System

Mac OSX

**Comment by josecannete** [comment]
Same problem here, I've downgraded to 2.4.7.

**Comment by xadips** [comment]
Having the same issue with web also when upgrading server in docker to 24.8.0-alpine.

**Comment by psybers** [comment]
This is a duplicate of #2705.

**Comment by Gazook89** [comment]
I have this same issue.  I just got started with Actual for the first time last night so I can't comment on changes over time, but will be going with the previous version for now.

On MacOS.

**Comment by haufhun** [comment]
Same issue here as well

**Comment by MikesGlitch** [comment]
Would anyone be able to reproduce the error on the latest build and then run the following steps:

- Select "View" > "Toggle Developer Tools" (or shortcut Cmd+shift+I) 
![image](https://github.com/user-attachments/assets/ebfcc15a-0f56-4a4e-a5d8-e151a4b4141f)
- Click on the "Console" tab of the window that opens 
![image](https://github.com/user-attachments/assets/7c2f3b01-8a52-4027-adb9-ad1ba52eb717)
- Press F5 (to refresh the page)
- Then copy the contents of the "Console" 

If you can paste the contents of the console in here it will help those of us without a mac.

**Comment by olets** [comment]
On Sonoma 14.5, F5 after opening the developer tools doesn't trigger a reload for me. I can trigger a reload by

1. opening the developer tools
2. clicking on the developer tools
3. shift-command-p
4. typing "reload"
5. clicking "reload page"

(no console messages to share because I'm on 24.7.0. Waiting for #2907 so I can make a backup before trying an upgrade)

**Comment by MikesGlitch** [comment]
I've got a fresh build up here: https://github.com/actualbudget/actual/actions/runs/10319828575?pr=3220

I'm looking for 2 testers, one with a x64 machine and one with an arm64 machine.

I'm expecting the x64 machine to work and the arm64 machine to fail - but want to double check before I try anything else.

For the testers: 
- Can you install the dmg file appropriate for your arch - there's 2: x64 and arm64

**Comment by mt-TechJourney** [comment]
@MikesGlitch The x64 is working on my M1 Pro but the arm64 is not.

**Comment by MikesGlitch** [comment]
> @MikesGlitch The x64 is working on my M1 Pro but the arm64 is not.

Sweet - can you try this one with your arm64 cpu?

https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220

**Comment by mt-TechJourney** [comment]
@MikesGlitch

![image](https://github.com/user-attachments/assets/9996c152-95b3-46a3-9f87-f8e82f258299)

Getting this error for the arm64. The other one (x64) is working.

**Comment by MikesGlitch** [comment]
> @MikesGlitch
> 
> ![image](https://private-user-images.githubusercontent.com/177056470/356790171-9996c152-95b3-46a3-9f87-f8e82f258299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODA1NDcsIm5iZiI6MTcyMzI4MDI0NywicGF0aCI6Ii8xNzcwNTY0NzAvMzU2NzkwMTcxLTk5OTZjMTUyLTk1YjMtNDZhMy05Zjg3LWY4ZTgyZjI1ODI5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQwODU3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDVmYmQyZDNlODdhMWE1ZmYyMjE0MmE5Y2ZlNGUyYzU1MzQ5MGRiZWRlMmViMjI2YjVmOTMzZmJmNzdkYWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VjJuZTpU3KOEsRwWulHfi-rTA3JNC_PA3koQ8JnlRMg)
> 
> Getting this error for the arm64. The other one (x64) is working.

Thanks for checking. I think this _may_ have to do with this: https://github.com/electron-userland/electron-builder/issues/8191

The article says you can get around it by running this command on your mac, can you give it a go?

```
 xattr -c <path/to/application.app>
```

It says it has something to do with app notarization, which we plan on fixing but need to make sure the builds are functioning first.

**Comment by kennydrobnack** [comment]
> > @MikesGlitch The x64 is working on my M1 Pro but the arm64 is not.
> 
> Sweet - can you try this one with your arm64 cpu?
> 
> https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220

I tried this and had to use the xattr -c command on the .app to get around the error message saying the app is damaged.

After I got into the console logs, it's pretty clear what's going on. Some part of the app is using Intel bits instead of arm. I triple checked to make sure the app I was running is the Apple Silicon version.

Here's the full error message:

console.error('Server Log:', "[Exception] Error: dlopen(/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0, 0x0001): tried: '/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (no such file), '/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (no such file), '/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))\n    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)\n    at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)\n    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)\n    at Module.load (node:internal/modules/cjs/loader:1214:32)\n    at Module._load (node:internal/modules/cjs/loader:1030:12)\n    at c._load (node:electron/js2c/node_init:2:13672)\n    at Module.require (node:internal/modules/cjs/loader:1242:19)\n    at require (node:internal/modules/helpers:176:18)\n    at bindings (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)\n    at new Database (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {\n  code: 'ERR_DLOPEN_FAILED'\n}\n")

**Comment by MikesGlitch** [comment]
> > > @MikesGlitch The x64 is working on my M1 Pro but the arm64 is not.
> > 
> > 
> > Sweet - can you try this one with your arm64 cpu?
> > https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220
> 
> I tried this and had to use the xattr -c command on the .app to get around the error message saying the app is damaged.
> 
> After I got into the console logs, it's pretty clear what's going on. Some part of the app is using Intel bits instead of arm. I triple checked to make sure the app I was running is the Apple Silicon version.
> 
> Here's the full error message:
> 
> console.error('Server Log:', "[Exception] Error: dlopen(/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0, 0x0001): tried: '/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (no such file), '/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (no such file), '/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))\n at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)\n at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)\n at Object.func [as .node] (node:electron/js2c/node_init:2:2441)\n at Module.load (node:internal/modules/cjs/loader:1214:32)\n at Module._load (node:internal/modules/cjs/loader:1030:12)\n at c._load (node:electron/js2c/node_init:2:13672)\n at Module.require (node:internal/modules/cjs/loader:1242:19)\n at require (node:internal/modules/helpers:176:18)\n at bindings (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)\n at new Database (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {\n code: 'ERR_DLOPEN_FAILED'\n}\n")

That's so bizarre because the PR built bettersqlite specifically for the arch. 🤔 

That error would have made sense before, because the release was being built on @MatissJanis so machine it would have had x64 bettersqlite, the update I pushed should have built arm64 in the Actual-mac-arm64.dmg. 

One last test before I completely change approach - this PR has a Universal build - it's our current release. 
https://github.com/actualbudget/actual/actions/runs/10334163398?pr=3231

It's built on an arm64 machine, so it doesn't make any sense that it could have x64 bettersqlite. 

Can you try it out and see if it gives the same error on your arm machine?

**Comment by kennydrobnack** [comment]
> > > > @MikesGlitch The x64 is working on my M1 Pro but the arm64 is not.
> > > 
> > > 
> > > Sweet - can you try this one with your arm64 cpu?
> > > https://github.com/actualbudget/actual/actions/runs/10322929844?pr=3220
> > 
> > 
> > I tried this and had to use the xattr -c command on the .app to get around the error message saying the app is damaged.
> > After I got into the console logs, it's pretty clear what's going on. Some part of the app is using Intel bits instead of arm. I triple checked to make sure the app I was running is the Apple Silicon version.
> > Here's the full error message:
> > console.error('Server Log:', "[Exception] Error: dlopen(/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0, 0x0001): tried: '/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (no such file), '/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (no such file), '/private/var/folders/3q/f_7507pn20d28hc11nlvntb80000gn/T/.com.actualbudget.actual.aULCS0' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))\n at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)\n at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)\n at Object.func [as .node] (node:electron/js2c/node_init:2:2441)\n at Module.load (node:internal/modules/cjs/loader:1214:32)\n at Module._load (node:internal/modules/cjs/loader:1030:12)\n at c._load (node:electron/js2c/node_init:2:13672)\n at Module.require (node:internal/modules/cjs/loader:1242:19)\n at require (node:internal/modules/helpers:176:18)\n at bindings (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)\n at new Database (/Applications/Actual.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {\n code: 'ERR_DLOPEN_FAILED'\n}\n")
> 
> I noticed a electron-rebuild was saying it succeeded when it didn't do anything. I think I fixed it.
> 
> Can someone try this one on an arm64 cpu? https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220

I haven't had a chance to put it through its paces, but it is able to open a budget from my Actual server. Looks like it's fixed. Thanks!

**Comment by melz** [comment]
> Can someone try this one on an arm64 cpu? https://github.com/actualbudget/actual/actions/runs/10339466938?pr=3220

Just tried this the arm64 on a M2. I also had to execute the `xattr -c` command on the .app to get around the error message saying the app is damaged but it does work after.

**Comment by MikesGlitch** [comment]
I have a PR up with the fix, thanks everyone for the help! 🚀

**Comment by MikesGlitch** [comment]
Fixed by https://github.com/actualbudget/actual/pull/3220

**Comment by asherljh** [comment]
Hi there, I'm running v24.9.0 but am still running into this issue. Interestingly, I encounter "We had an unknown problem opening "My-Finances-79046ea" on Firefox on my AMD computer, and my Xiaomi 14, but not on Firefox on my Zenfone 9. 

![image](https://github.com/user-attachments/assets/dfb48491-43b4-410f-a031-1b2454711bf6)

On my computer, it works in the Actual desktop app.

If I create a new file / import my data from the Actual exported .zip, I will be able to access the file for a short while but after I refresn the page a few times I will end up with the error again. Any help? Thanks!

**Comment by T3chGuy77** [comment]
This issue is not fixed or resolved. I still have it on the current version.

**Comment by MikesGlitch** [comment]
> This issue is not fixed or resolved. I still have it on the current version.

What do you see when you open devtools? It's under the View menu > Toggle developer tools.

Can you copy and paste the error here?

**Comment by mehrmoudi** [comment]
I just ran into this issue. It doesn't happen the first time I open the budget and it downloads it. But every time after it keeps happening. I have to clear browser data/cache to be able to work with my budget.

I see the following message in the console:
```
[Exception] Error: database disk image is malformed
    at c.handleError (sql-wasm.js:89:129)
    at a.step (sql-wasm.js:80:69)
    at runQuery (index.web.ts:77:19)
    at loadSpreadsheet (sheet.ts:153:30)
    at budgetfiles_app_loadBudget (app.ts:590:11)
    at async app_loadBudget (app.ts:239:15)
``` 

Versions: `App: v25.5.0 | Server: v25.5.0`

**Comment by MikesGlitch** [comment]
Just so everyone knows, that error in that screenshot in the description is a catch-all error. The initial issue here was to do with how better-sqlite was built - which is fixed.

To keep our Github clean(ish) and to give your issues more attention, can you please open a new issue with the information form the devtools logs. There's no point in adding comments to this Issue becuase there's loads of potential problems related to this one user-facing error. We can't tackle them all in one issue.

@MuffinBeast That one looks like a migration error. First thing to do is ensure you have HTTPS setup/running from localhost.
