### ISSUE TITLE
[Bug]: SimpleFin Bank Sync network-error

### ISSUE THREAD

**Issue by rljes** [actualbudget/actual#4480]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

For the past few weeks I have periodically (on a few days, off a few days) encountered an issue trying to 'Bank Sync' on All accounts. Individual accounts work okay. All accounts loads a while and then pops up many red "network-failure" boxes.

I have 35 sync'd accounts across 12 or so institutions. I think it is popping up 35 errors, but I never count them; I just refresh the page.

*perhaps only display one error, not one per account*

The console logs are
```
Using SimpleFin batch sync
Bank Sync operations for all SimpleFin accounts
    Pulling transactions from SimpleFin
Syncing since <datetime string> 0 (attempt: 0)
Got messages from server 0
```

Syncing one account works fine, but as mentioned there are 35 total...that is a lot of work.

*perhaps be able to select a subset of accounts to sync*

To contrast with a single account sync, here are those console logs
```
Bank Sync operation for account: <name>
    Pulling transactions from SimpleFin
    Response: <obj>
    Performing transaction reconciliation
    Performing transaction reconciliation matching
    Debug data for the operations: <obj>
Syncing since <datetime string> 0 (attempt: 0)
Got messages from server 0
```

The Sync All logs have basically no information. I suspect some internal timeout that gets simplified to 'network-error'.

### How can we reproduce the issue?

1. Set up ~35 SimpleFin linked accounts
2. 'Bank Sync' from 'All accounts'
3. Hope to get unlucky

Seen on my mobile device as well, but no access to console logs there.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by matt-fidd** [comment]
Thanks for reporting! We've seen similar reports in the Discord and a user has approached SimpleFIN. The correspondence they've received so far is as follows:

------

> I believe this is a combination of things. To your knowledge, has Actual always requested 90 days worth of transactions? Reducing that to something like a month's worth of data would help.
> 
> We also have plans to allow for requests that take several minutes, but that will take a little while.

-----

> We'll be rolling out a change soon (still need to do a lot of testing to make sure we don't break anything), but the change will require that requests to the API follow HTTP redirects correctly.
> 
> Specifically, GET /simplefin/accounts will possibly return
> 
> HTTP 307 Temporary Redirect
> 
> with the Location header set to the URL the client should follow. I can't seem to access the Discord you linked (don't know why), but are you able to find out if Actual's HTTP client follow redirects? Or can you point me to a GitHub issue/PR?

This is a recent issue, which suggests that it's a problem on the SimpleFIN side. There are things we can look into on our side (reducing sync from 90 days of data or batching smaller amounts of accounts) but they wouldn't be released until the next version v25.4 (start of April). Hopefully we can work with them to implement their redirect solution before then.

If you're an edge user I'll probably implement a quick fix at the start of the next release cycle to split the batched request into a few smaller ones.

**Comment by rosiebug** [comment]
I've been having sync issues with SimpleFIN for almost 2 weeks now, and finally came looking to see if it is affecting anyone else. Essentially zero transaction imports since it started, and pops up the red error message to report on github. That's what brought me here...

Hopefully there's a fix soon!
If helpful, these are the bank connections I use:
Tangerine
Wealthsimple
Scotiabank
PC Financial

None of them work right now.

**Comment by markusthiel** [comment]
I think this also affects GoCardless. I am experiencing this issue in the latest version v25.3.1 as well.

**Comment by pacbidouandco** [comment]
I confirm, the synchronization has not worked since the update

**Comment by junalmeida** [comment]
I 'm not sure this is related to this issue or different, because the "Internal Message" error is generic, but I could catch this from the network call, using SimpleFIN:

![Image](https://github.com/user-attachments/assets/d2d3b4eb-5b71-4594-ad08-e73fa82fded4)

I guess Actual could show to the user a proper message when an account needs attention.

**Comment by RSXEnthusiast** [comment]
I can also confirm that my internal errors are due to accounts needing attention. I had two errors pop up on sync, and had two accounts that needed attention in SimpleFIN. Fixing these accounts made the internal errors go away.

As for what Actual should do when encountering these errors, it actually (pun intended) used to show a nice notification on the account page mentioning that it needs attention, so this is just a recently introduced bug that broke that behavior.

**Comment by matt-fidd** [comment]
> I can also confirm that my internal errors are due to accounts needing attention. I had two errors pop up on sync, and had two accounts that needed attention in SimpleFIN. Fixing these accounts made the internal errors go away.
> 
> As for what Actual should do when encountering these errors, it actually (pun intended) used to show a nice notification on the account page mentioning that it needs attention, so this is just a recently introduced bug that broke that behavior.

Yep, good spot. It's been fixed on edge now and we've got our nice error messages back. They'll be fixed in the next release.

**Comment by matt-fidd** [comment]
Closing this now, I've not seen any complaints of the timeout issue since the change has been introduced.

**Comment by sexyskinnybitch** [comment]
This is not fixed, it is still occurring for me on pikapods.

**Comment by pcgirl** [comment]
I am still getting this error when I try to sync my accounts.  I have just setup pikapods and simplefin but it doesn't sync the accounts without an error.  Simplefin shows no issues with the accounts.  I don't know what version the Actual is on pikapods.  I don't see a version anywhere.

**Comment by babehboi** [comment]
I'd say this issue may or may not be resolved as I cannot determine why it keeps happening. I'd say I noticed this in the past 2 weeks or so as well with SimpleFin and have been trying to find a resolution for it as well.

**Comment by chrwei** [comment]
Still getting timeouts.  I don't thin it's a 90 days issue.  i just tested single account sync with an account that only has 1 transaction in the last 90 days it also timed out.

"type: 'BankSyncError', category: 'TIMED_OUT', code: 'TIMED_OUT', details: undefined, message: 'Failed syncing account...."

SimpleFIN's website is also running a bit slow, and while not 60 seconds+ slow, maybe the 60 second timeout just isn't enough.
