### ISSUE TITLE
[Bug]: Entering an amount and then pressing Cleared toggle clears the amount

### ISSUE THREAD

**Issue by parapsychic** [actualbudget/actual#6056]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

I usually use the add transaction page to track my transactions. On mobile, when I enter an amount and then immediately click the cleared toggle, the amount vanishes. 

https://github.com/user-attachments/assets/526ddb17-5f63-46e9-ba89-56dba385d829

### How can we reproduce the issue?

On Chrome (Android)

- Click on Add Transaction
- Enter an amount
- Without pressing back or letting the keyboard close, check the "Cleared" toggle.
- The amount disappears

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by parapsychic** [comment]
I've checked this issue, and I think I know why this happens. It is like a race condition.

- The amount is saved to state (persisted to local db too) on the `onBlur` event of the amount component. This event calls an `onUpdateInner` event, which in turn calls the `onUpdate` callback with the current state of the transaction (where amount = 0) passed into the callback.
- The `onUpdate` callback has some asynchronous code, so while that happens, the `onToggle` function of the Cleared component calls the `onUpdateInner`. This also calls the  `onUpdate` callback with a stale transaction state (where amount = 0).
- The first callback returns from doing the async task and updates state to reflect the transaction (sets transaction.amount = X)
- But the second callback from the cleared component overwrites the state again making transaction.amount = 0.

I've tried my best to fix this, but the code seems too complex imo for doing this simple task.  But then again, I'm not really good at React, so 🤷. The issue 100% stems from passing the entire transaction state around and trusting the component to provide the transaction's state to update the transaction's state of the entire page.

Hopefully someone else can look into this and fix it, because now I have a whole bunch of zero transactions which I have no idea where it came from 🤣

**Comment by CrimsonFlash** [comment]
This also happens on the non-mobile browser and native macOS apps.

Solution I have found on desktop in the interim is to tab over before pressing the cleared button.

**Comment by adamu** [comment]
I started seeing this on Desktop after upgrading to 26.4.0

**Comment by parapsychic** [comment]
This issue has been fixed in latest update.

**Comment by adamu** [comment]
@parapsychic I have just updated to the latest (26.7.0) update and the problem persists.

**Comment by adamu** [comment]
Here is a video. I cannot reproduce it on https://demo.actualbudget.org though. Both are on v26.7.0

https://github.com/user-attachments/assets/eb88593d-2e47-42c1-aa07-fb7b004a659f

**Comment by parapsychic** [comment]
@adamu I had made this issue for mobile. Also, I could not reproduce this on my desktop version as well. Are you sure your browser doesn't have some cached version of the page? Try doing a hard refresh.

**Comment by PositiveMD** [comment]
@parapsychic I am also running into the same issue as well. I have the instance hosted on pikapods (if that helps), and the issue occurs when I use the desktop browser interface.

**Comment by parapsychic** [comment]
@PositiveMD @adamu 
I could actually replicate this issue and I've made the fix. I'll raise a PR in sometime after some checks.
